name: ci/cd react app

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

permissions: 
  contents: write

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: install ci
        run: npm ci
      
      - name: Build the Project
        run: npm run build

      #configure git identity
      - name: Configure Git
        run: |
          git config --global user.name AsapuPraveena
          git config --global user.email praveenasai12072005@gmail.com
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          npm run deploy